// <auto-generated />
using System;
using BookMyShow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookMyShow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260123054446_SeedMovieShowsAndSeats")]
    partial class SeedMovieShowsAndSeats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookMyShow.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieShowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BookMyShow.Domain.Entities.MovieShow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScreenNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MovieShows");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            MovieTitle = "Spider-Man: No Way Home",
                            ScreenNumber = "Screen 2",
                            ShowTime = new DateTime(2026, 1, 24, 16, 56, 45, 0, DateTimeKind.Utc),
                            TotalSeats = 75
                        },
                        new
                        {
                            Id = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            MovieTitle = "Avengers: Endgame",
                            ScreenNumber = "Screen 1",
                            ShowTime = new DateTime(2026, 1, 23, 16, 56, 45, 0, DateTimeKind.Utc),
                            TotalSeats = 100
                        });
                });

            modelBuilder.Entity("BookMyShow.Domain.Entities.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieShowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7979b07-b4a4-4f74-85b1-f74ceb3ad1fc"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "A1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("37cc5866-1bc0-4be9-8480-50b64e190a47"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "A1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("25bd6cb9-151b-4af4-896d-3d5234e8a026"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "A2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("4ff99623-beac-4d44-b72d-dccf39c25c02"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "A2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("b1e1c4a4-080b-4e9b-bd52-c71122d57932"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "A3",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("a35b9587-3128-4af6-ab6e-506b1c29bde2"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "A3",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("9aaed74c-ffbf-482a-a4bf-65ff0e495170"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "B1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("9045ded9-96b2-4da1-8f16-3ad36b639993"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "B1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("9014dc60-7617-48df-8dc4-73a8270105e9"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "B2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("4b1f7d23-4101-49f9-b0d1-126c33fc9c77"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "B2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("dab26cb5-b082-4f22-b967-94cbe803267c"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "C1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("57f1c2f3-ddab-4b3d-88e5-00af99aeb1de"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "C1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("cbeed942-ded8-49e3-9cd1-ff9afc0a7c35"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "C2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("018e9370-bc81-460c-a203-7469f47844d0"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "C2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("42fd7d61-c0af-43d9-90b6-7b801dc68985"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "C3",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("8f4dd792-c487-4837-a1f0-440f6c2b3135"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "C3",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("b17d1910-1380-49f3-b7f9-da71e68f6ec0"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "D1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("35c28339-ae97-48f7-a72a-bd1435fcfe43"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "D1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("52612dd3-a813-42c5-a8bc-4bdac9d3895a"),
                            MovieShowId = new Guid("67d35d72-2fdc-4c6e-a5b1-6a2eb7503c16"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "D2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = new Guid("795e3a99-e18a-4785-80d5-3322b04d37e2"),
                            MovieShowId = new Guid("f525ebb5-623f-4779-bbaa-79557d2b909d"),
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            SeatNumber = "D2",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("BookMyShow.Domain.Entities.Seat", b =>
                {
                    b.HasOne("BookMyShow.Domain.Entities.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId");
                });
#pragma warning restore 612, 618
        }
    }
}
